server:
  port: 8082
spring:
  application:
    name: producer

# dubbo配置
dubbo:
  application:
    id: dubbo-producer # 自己定义
    name: dubbo-producer # 自己定义
  monitor:
    protocol: dubbo-registry
  registry:
    address: nacos://localhost:8848 # 自己定义, 写自己的nacos的ip地址, 8848是默认端口 ;
  config-center:
    address: nacos://localhost:8848 # 自己定义, 写自己的nacos的ip地址, 8848是默认端口 ;
  metadata-report:
    address: nacos://localhost:8848 # 自己定义, 写自己的nacos的ip地址, 8848是默认端口 ;
  provider: # 具体参数含义, 查看官方文档
    threadpool: fixed
    threads: 10
    loadbalance: roundrobin
    timeout: 8000
    retries: 3
  protocol:
    name: dubbo
    port: 28080

# nacos配置, 具体参数,参照官方文档
nacos:
  discovery:
    register:
      healthy: false
      service-name: HelloService
      group-name: tom
    server-addr: localhost:8848 # 自己定义, 写自己的nacos的ip地址, 8848是默认端口 ;
